# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-19 01:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='worker',
        ),
        migrations.AddField(
            model_name='user',
            name='jobs',
            field=models.ManyToManyField(related_name='users', to='main.Job'),
        ),
    ]
