# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-22 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='join',
            field=models.ManyToManyField(related_name='joiner', to='main.User'),
        ),
    ]
